name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install packages and run tests
        run: |
          yarn
          yarn lint
